### ISSUE TITLE
Unable to connect to battle net

### ISSUE THREAD

**Issue by CAPsMANyo** [shupershuff/Diablo2RLoader#39]
I'm unable to connect to battle net. I'm using simple password auth, no MFA.   My accounts.csv looks like this

```
ID,Acct,AccountLabel,Batches,TimeActive,CustomLaunchArguments,AuthenticationMethod,PW,Token
1,email1@gmail.com,account1,,,,Parameter,password1,
2,email2@gmail.com,account2,,,,Parameter,password2,
```
When I run the launcher I see this error before it eventually goes the the menu.  I'm able to launch instances but none can connect to battle.net

![Screenshot 2024-06-15 215816](https://github.com/shupershuff/Diablo2RLoader/assets/46333588/746c8760-71c2-4d1b-9c7c-ecf1eb9a0696)

**Comment by shupershuff** [comment]
Did you obtain account.csv from the latest release zip or directly from this Github page?
Don't download accounts.csv from the repo directly, I've edited it for the new version which I'll be releasing soon as the new script will no longer use the PWIsSecureString column.

**Comment by CAPsMANyo** [comment]
I had clones the entire repo.  I'll try downloading the release.

**Comment by shupershuff** [comment]
> I had clones the entire repo. I'll try downloading the release.

Blame my GitHub inexperience/incompetence for that :)

**Comment by CAPsMANyo** [comment]
I'm now using the releases zip.  No errors in the program, but both accounts say "Cannot connect to server"

**Comment by shupershuff** [comment]
I just released the new version which may help (made it a bit easier to reset passwords).
If it's not connecting then it's one of the following issues:

- Account email or Password is wrong. Open browser in private mode and try sign into https://battle.net to see if you have the right credentials.
- Account has MFA enabled on it which doesn't work with parameter authentication. If this is the case you need to either disable MFA or use Auth Token method instead of Parameters. See setup instructions.
- Account is "locked due to suspicious activity". Login to Battle.net website and check for any captcha's/security prompts. Do the same in the battle.net client. Using Authentication tokens instead of parameters is also a way around this.
- Region is temporarily locked out after too many failed authentication attempts with the wrong password. If you think this is the issue you can try a different region.

**Comment by CAPsMANyo** [comment]
I'm actually still having the same issue with the latest release.  I added this write-output on line 2946

```
if ($Script:AccountChoice.AuthenticationMethod -eq "Parameter" -and $Script:ForceAuthToken -ne $True -and $Script:Config.ForceAuthTokenForRegion -notmatch $RegionLabel){
	$arguments = (" -username " + $Script:acct + " -password " + $Script:PW + " -address " + $Script:Region + " " + $CustomLaunchArguments).tostring()
	Write-Host = $arguments
}
```

And when it outputs, after the -username is blank.  Happens with either account I'm using.  I'll do some more debugging and see if I can figure out where it drops.

**Comment by shupershuff** [comment]
After -username it should show the email address of the account that your signing into. It must be an issue with what's in accounts.csv. What does your accounts.csv look like? Does it look something like this:

"1","your.email@email.com","BO Barb","","3.16:00:12.5809042","","Parameter","<SECUREDPW>","<SECUREDTOKEN>"

Contact me via Discord if you want to share anything you don't feel comfortable sharing here, my username is Shupershuff.

**Comment by CAPsMANyo** [comment]
Thanks, I messaged you on discord.

**Comment by CAPsMANyo** [comment]
Issue related to ConvertPlainTextPassword being set to false.  Leave True to avoid issues.  Also recommend switching all accounts to Token based auth instead of password.

**Comment by shupershuff** [comment]
> Issue related to ConvertPlainTextPassword being set to false. Leave True to avoid issues. Also recommend switching all accounts to Token based auth instead of password.

Thanks for your feedback and testing! Issue with ConvertPlainTextPassword will be fixed in next release.
I've updated readme to further highlight Auth Token setup step for problematic accounts.

Cheers!
